In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(f'../dataset/dataset-tickets-multi-lang-4-20k.csv', encoding='utf-8')

In [5]:
len(df.columns)

15

In [6]:
len(df)

20000

In [7]:
df.columns

Index(['subject', 'body', 'answer', 'type', 'queue', 'priority', 'language',
       'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6', 'tag_7', 'tag_8'],
      dtype='str')

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   18539 non-null  str
 1   body      19998 non-null  str
 2   answer    19996 non-null  str
 3   type      20000 non-null  str
 4   queue     20000 non-null  str
 5   priority  20000 non-null  str
 6   language  20000 non-null  str
 7   tag_1     20000 non-null  str
 8   tag_2     19954 non-null  str
 9   tag_3     19905 non-null  str
 10  tag_4     18461 non-null  str
 11  tag_5     13091 non-null  str
 12  tag_6     7351 non-null   str
 13  tag_7     3928 non-null   str
 14  tag_8     1907 non-null   str
dtypes: str(15)
memory usage: 2.3 MB

In [10]:
df[df['language'] == 'en'].head()

,subject,body,answer,type,queue,priority,language,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
1,Customer Support Inquiry,Seeking information on digital strategies that...,We offer a variety of digital strategies and s...,Request,Customer Service,medium,en,Feedback,Sales,IT,Tech Support,NaN,NaN,NaN,NaN
2,Data Analytics for Investment,I am contacting you to request information on ...,I am here to assist you with data analytics to...,Request,Customer Service,medium,en,Technical,Product,Guidance,Documentation,Performance,Feature,NaN,NaN
4,Security,"Dear Customer Support, I am reaching out to in...","Dear [name], we take the security of medical d...",Request,Customer Service,medium,en,Security,Customer,Compliance,Breach,Documentation,Guidance,NaN,NaN
5,Concerns About Securing Medical Data on 2-in-1...,Inquiring about best practices for securing me...,Thank you for your concern regarding securing ...,Request,Technical Support,medium,en,Security,Product,Feature,IT,Tech Support,NaN,NaN,NaN
7,Problem with Integration,"The integration stopped working unexpectedly, ...",I will look into the problem and call you at <...,Problem,IT Support,high,en,Technical,Integration,Bug,Resolution,Outage,Documentation,NaN,NaN

In [11]:
len(df[df['language'] == 'en'])

11923

In [13]:
df.describe().T

,count,unique,top,freq
subject,18539,18539,Unvorhergesehener Absturz der Datenanalyse-Pla...,1
body,19998,19998,Die Datenanalyse-Plattform brach unerwartet ab...,1
answer,19996,19996,Ich werde Ihnen bei der Lösung des Problems he...,1
type,20000,4,Incident,7978
queue,20000,10,Technical Support,5824
priority,20000,3,medium,8144
language,20000,2,en,11923
tag_1,20000,148,Technical,5034
tag_2,19954,204,Performance,2795
tag_3,19905,344,IT,3309
tag_4,18461,481,Tech Support,3436
tag_5,13091,578,Tech Support,2287
tag_6,7351,566,Resolution,841
tag_7,3928,492,Resolution,417
tag_8,1907,386,Documentation,162

In [17]:
for i in ['type', 'priority', 'queue', 'language']:
    print(f'Unique values for {i}: {df[i].unique()}\n')

Unique values for type: <StringArray>
['Incident', 'Request', 'Problem', 'Change']
Length: 4, dtype: str

Unique values for priority: <StringArray>
['low', 'medium', 'high']
Length: 3, dtype: str

Unique values for queue: <StringArray>
[                'General Inquiry',                'Customer Service',
               'Technical Support',                      'IT Support',
                 'Product Support',            'Billing and Payments',
 'Service Outages and Maintenance',                 'Human Resources',
           'Returns and Exchanges',             'Sales and Pre-Sales']
Length: 10, dtype: str

Unique values for language: <StringArray>
['de', 'en']
Length: 2, dtype: str

In [41]:
for i in df.columns:
    print(f"{i}: {df[i].isnull().sum()}, {df[i].isnull().sum()/len(df)*100:.2f}% null values\n")

subject: 1461, 7.31% null values

body: 2, 0.01% null values

answer: 4, 0.02% null values

type: 0, 0.00% null values

queue: 0, 0.00% null values

priority: 0, 0.00% null values

language: 0, 0.00% null values

tag_1: 0, 0.00% null values

tag_2: 46, 0.23% null values

tag_3: 95, 0.47% null values

tag_4: 1539, 7.70% null values

tag_5: 6909, 34.54% null values

tag_6: 12649, 63.24% null values

tag_7: 16072, 80.36% null values

tag_8: 18093, 90.46% null values

In [65]:
body_duplicates = df.duplicated(subset=["body"]).sum()
subject_body_duplicates = df.duplicated(
    subset=["subject", "body"]
).sum()

print(f"Duplicates by body: {body_duplicates}")
print(f"Duplicates by subject + body: {subject_body_duplicates}")

Duplicates by body: 1
Duplicates by subject + body: 0

In [26]:
for i in ['type', 'priority', 'queue', 'language']:
    print(f'Unique values for {i}: {df[i].value_counts()}\n')

Unique values for type: type
Incident    7978
Request     5763
Problem     4184
Change      2075
Name: count, dtype: int64

Unique values for priority: priority
medium    8144
high      7801
low       4055
Name: count, dtype: int64

Unique values for queue: queue
Technical Support                  5824
Product Support                    3708
Customer Service                   3152
IT Support                         2292
Billing and Payments               2086
Returns and Exchanges              1001
Service Outages and Maintenance     764
Sales and Pre-Sales                 572
Human Resources                     338
General Inquiry                     263
Name: count, dtype: int64

Unique values for language: language
en    11923
de     8077
Name: count, dtype: int64

In [60]:
body_lengths = df["body"].fillna("").astype(str).str.len()
body_lengths.nlargest(3)

4616     2259
2434     1802
16604    1793
Name: body, dtype: int64

In [62]:
body_lengths.nsmallest(5)

17687    0
17959    0
549      4
17666    5
10560    7
Name: body, dtype: int64

In [43]:
sum = 0
nan_count = 0
for i in df['body']:
    try:
        sum += len(i)
    except:
        nan_count += 1

print(f"{sum/(len(df['body']) - nan_count):.4f}")

394.4775

In [45]:
arr_median = []
for i in df['body']:
    try:
        arr_median.append(len(i))
    except:
        pass
arr_median.sort()
if len(arr_median) % 2 == 0:
    median = (arr_median[len(arr_median)//2] + arr_median[len(arr_median)//2 - 1]) / 2
else:
    median = arr_median[len(arr_median)//2]

print(median)

357.0

In [63]:
sample = df.sample(n=5, random_state=42)

for _, row in sample.iterrows():
    print(f"Queue: {row['queue']}")
    print(f"Type: {row['type']}")
    print(f"Body: {row['body']}")
    print("-" * 80)

Queue: Technical Support
Type: Problem
Body: Es gab einen medizinischen Datenverlust aufgrund mangelnder Verschlüsselung und veralteter Apache Hadoop. Es wurde unerlaubter Zugriff auf Patientendaten registriert. Wir haben MongoDB aktualisiert und Cassandra neu gestartet, aber das Problem behält sich beständig bei.
--------------------------------------------------------------------------------
Queue: IT Support
Type: Incident
Body: I'm encountering difficulties with the medical data encryption process. It suddenly stopped working, and I believe it could be because of compatibility issues with Redis 6.2. I've already restarted my NZXT Kraken Z63 and reviewed my iOS 15 settings, but the problem still isn't resolved. I'd appreciate your help in addressing this issue quickly.
--------------------------------------------------------------------------------
Queue: Technical Support
Type: Change
Body: Ich möchte eine Erweiterungsvorschlag für die Datenverarbeitung und Investitionsoptimierung einreichen. Bitte stellen Sie sicher, dass die Integration in betroffene Produkte kompatibel ist, um die Gesamtleistung zu verbessern.
--------------------------------------------------------------------------------
Queue: Billing and Payments
Type: Request
Body: Welche Zahlungsmöglichkeiten gibt es?
--------------------------------------------------------------------------------
Queue: IT Support
Type: Change
Body: Customer Support, please address the request for the implementation of enhanced security protocols for medical data access and communication systems across all affected products and services. It is crucial to ensure the confidentiality and integrity of sensitive medical information. Could you provide details on the measures that have been taken to address this issue and the timeline for expected implementation? We look forward to your prompt response and appreciate your attention to this matter. Kindly inform us if there is any additional information needed to facilitate the process.
--------------------------------------------------------------------------------